### ISSUE TITLE
Allow semver as parameter for release jobs

### ISSUE THREAD

**Issue by jlmadurga** [tinybirdco/ci#30]
Release jobs uses by default `.tinyenv` current version. It is ok for most cases except when removing one arbitrary release.

Add input parameter on release jobs to pass semver

**Comment by alrocar** [comment]
I added a job to `tb release rm --oldest-rollback` that should do the trick when you need to free resources, for the rest of jobs I guess it's fine running them against the .tinyenv version

**Comment by alrocar** [comment]
We removed deletion jobs to avoid mistakes
