### ISSUE TITLE
Custom CI branch name

### ISSUE THREAD

**Issue by maluframer** [tinybirdco/ci#89]
Would it be possible to add an optional `branch_name` input to the CI workflow? That would allow us to call the provided workflow and deprecate our own custom one.

**Comment by alrocar** [comment]
what will that `branch_name` used for?

**Comment by maluframer** [comment]
> what will that `branch_name` used for?

@alrocar it should be then used as the actual branch name when the branch is created in the workspace, now it's defined [here](https://github.com/tinybirdco/ci/blob/main/.github/workflows/ci.yml#L96). 

But I realize now that passing an argument wouldn't work, as we still want the branch name to be dynamic, just with a different pattern (e.g `{user}_some_prefix_{PR_number}`)

**Comment by alrocar** [comment]
I guess you can export `_NORMALIZED_BRANCH_NAME` in .tinyenv to override it, not sure if that'd work for you.

```
export _NORMALIZED_BRANCH_NAME=whatever
```
